code/config/routes.rb
Rails.application.routes.draw do

  resources :classrooms
  resources :users

  root   'pages#home'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get   '/activate/:token', to: 'users#activate', as: :activate
  get    '/login',   to: 'users#login'
  post   '/login',   to: 'users#user_login'
  delete '/logout',  to: 'users#logout'
  get    '/password-reset', to: 'users#password_reset', as: :password_reset
  post    '/password-reset', to: 'users#send_new_password'
  get    '/password-reset/:token', to: 'users#choose_password', as: :choose_password
  patch    '/password-reset/:token', to: 'users#reset_password'
  get  '/subscribe/:id', to: 'subscriptions#new', as: :subscribe
  post '/subscribe/:id', to: 'subscriptions#create'

end

code/app/models/classroom.rb
class Classroom < ApplicationRecord
  has_secure_password

  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :name, presence: true
  validates :password, presence: true
  validates :minimum_grade, presence: true, if: :has_grades?

end

code/app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  include UsersHelper

  load_and_authorize_resource

  before_action :set_classroom, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:new, :create, :destroy]
  before_action :teacher_only, only: [:edit, :update]
  before_action :student_only, only: [:show]

  # GET /classrooms
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  def create
    @classroom = Classroom.new(classroom_params)

    if ManageClassroomService.new(@classroom).create
      redirect_to @classroom, notice: 'Classroom was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /classrooms/1
  def update
    if ManageClassroomService.new(@classroom).edit(classroom_params)
      redirect_to @classroom, notice: 'Classroom was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /classrooms/1
  def destroy
    ManageClassroomService.new(@classroom).delete
    redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def classroom_params
      params.require(:classroom).permit(:name, :password, :has_grades, :ha_attendance, :minimum_grade )
    end

    def admin_only
      current_user.admin?
    end

    def teacher_only
      unless current_user.admin? || current_user.subscriptions.where(classroom_id: @classroom.id).first.role == 'teacher'
        redirect_to subscribe_path(@classroom.id)
      end
    end

    def student_only
      unless current_user.admin? || current_user.subscriptions.where(classroom_id: @classroom.id).exists?
        redirect_to subscribe_path(@classroom.id)
      end
    end
end

code/app/helpers/classrooms_helper.rb
module ClassroomsHelper

  def students_count(classroom)
    ManageClassroomService.new(classroom).students_count
  end

end

code/app/views/classrooms/_form.html.erb
<%= form_for(classroom) do |f| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :has_grades %>
    <%= f.check_box :has_grades %>
  </div>

  <div class="field">
    <%= f.label :has_attendance %>
    <%= f.check_box :has_attendance %>
  </div>

  <div class="field">
    <%= f.label :minimum_grade %>
    <%= f.text_field :minimum_grade %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

code/app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

code/app/views/classrooms/index.html.erb
<% provide(:title, 'Turmas') %>

<div class="row">
  <% @classrooms.each do |classroom| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card classroom">
          <% if current_user.admin?  %>
              <div class="dropdown">
                <div data-target="#" data-toggle="dropdown" class="dropdown-toggle">
                  <%= fa_icon 'caret-down' %>
                </div>
                <ul class="dropdown-menu dropdown-menu-left">
                  <li><%= link_to 'Editar', edit_classroom_path(classroom) %></li>
                  <li><%= link_to 'Excluir', classroom, method: :delete, data: {confirm: 'Are you sure?'} %></li>
                </ul>
              </div>
          <% end %>
              <%= link_to classroom do %>
                  <div class="row table-row">
                    <div class="col-xs-12 col-md-4 table-cell">
                      <div class="students">
                        <p class="number text-center"><%= students_count(classroom) %></p>
                        <p class="text-center">alunos</p>
                      </div>
                    </div>
                    <div class="col-xs-12 col-md-8 table-cell middle">
                      <h2 class="classroom-title"><%= classroom.name %></h2>
                    </div>
                  </div>
                  </div>
              <% end %>
              </div>
          <% end %>
          </div>

          <div class="text-right">
            <%= link_to 'Nova turma', new_classroom_path, class: 'btn btn-primary' if current_user.admin? %>
          </div>

code/app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', classrooms_path %>

code/app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classroom.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @classroom.password %>
</p>

<p>
  <strong>Has grades:</strong>
  <%= @classroom.has_grades %>
</p>

<p>
  <strong>Has attendance:</strong>
  <%= @classroom.has_attendance %>
</p>

<p>
  <strong>Minimum grade:</strong>
  <%= @classroom.minimum_grade %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>