code/config/routes.rb
Rails.application.routes.draw do

  resources :classrooms
  resources :users

  root   'pages#home'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get   '/activate/:token', to: 'users#activate', as: :activate
  get    '/login',   to: 'users#login'
  post   '/login',   to: 'users#user_login'
  delete '/logout',  to: 'users#logout'
  get    '/password-reset', to: 'users#password_reset', as: :password_reset
  post    '/password-reset', to: 'users#send_new_password'
  get    '/password-reset/:token', to: 'users#choose_password', as: :choose_password
  patch    '/password-reset/:token', to: 'users#reset_password'
  get  '/subscribe/:id', to: 'subscriptions#new', as: :subscribe
  post '/subscribe/:id', to: 'subscriptions#create'

end

code/app/views/layouts/_content.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-2 col-sm-3 sidebar">
      Sidebar
    </div>
    <div class="col-xs-12 col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2">
      <div class="has-sidebar">
        <section class="page-title card">
          <div class="row">
            <div class="col-xs-12">
              <h1><%= yield(:title) %></h1>
            </div>
          </div>
        </section>
        <% unless current_page?(root_path) %>
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
        <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>
</div>

code/app/views/layouts/_favicon.html.erb
<% %w(57 60 72 76 114 120 144 152 180).each do |size| %>
    <%= favicon_link_tag "favicon/apple-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(36 48 72 96 144 192).each do |size| %>
    <%= favicon_link_tag "favicon/android-icon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(16 32 96).each do |size| %>
    <%= favicon_link_tag "favicon/favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<%= favicon_link_tag 'favicon/favicon.ico', rel: 'icon', type: 'image/ico', sizes: '16x16' %>

code/app/views/layouts/_footer.html.erb
<footer class="footer">

</footer>

code/app/views/layouts/_header.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-3">
        <div class="logo">
          <%= link_to image_tag('logo_header.png'), root_path %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-9 text-right">
        <% if logged_in? %>
          <div class="dropdown">
            <div data-target="#" data-toggle="dropdown" class="dropdown-toggle">
              <%= gravatar_for current_user, size: 50 %>
              <%= content_tag(:span, current_user.name )%>
              <%= fa_icon 'caret-down' %>
            </div>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to 'Ver Perfil', current_user %></li>
              <li><%= link_to 'Editar Perfil', edit_user_path(current_user) %></li>
              <li><%= link_to 'Sair', logout_path, method: 'delete' %></li>
            </ul>
          </div>
        <% else %>
          <div class="menu">
            <%= link_to('Entrar', login_path) %>
            <%= link_to('Cadastrar-se', signup_path, "class": 'btn') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

code/app/views/layouts/_nosidebar_content.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <section class="page-title card">
        <div class="row">
          <div class="col-xs-12">
            <h1><%= yield(:title) %></h1>
          </div>
        </div>
      </section>
      <% unless current_page?(root_path) %>
          <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
</div>

code/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

code/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= google_webfonts_init({
                               google: ['Roboto Condensed:300,400,700',
                                        'Roboto:300,400,500,700,900',
                                        'Raleway:300,400,500,700,800']
                           }) %>

  <%= render 'layouts/shim' %>
  <%= render 'layouts/favicon' %>
</head>
<body class="<%= body_class %>">
<% if current_page?(root_path) %>
    <div class="container">
      <%= yield %>
    </div>
<% else %>
    <%= render 'layouts/header' %>
    <%= render current_page?(signup_path) || current_page?(login_path) || current_page?(password_reset_path) ?
      'layouts/nosidebar_content' : 'layouts/content' %>
<% end %>
<% unless current_page?(root_path) %>
    <%= render 'layouts/footer' %>
<% end %>
</body>
</html>